"""Create a safe, ready-to-integrate external verification workspace."""

from __future__ import annotations

import csv
import ctypes
import errno
import json
import os
import shutil
import stat
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from . import __version__
from .runner import (
    ACTUAL_SCHEMAS,
    DEFAULT_CASES_DIR,
    INPUT_SCHEMAS,
    _load_case_contract,
    discover_cases,
)
from .verification import expected_verification_manifest


@dataclass(frozen=True)
class ScaffoldResult:
    """Summary of a newly created integration workspace."""

    destination: Path
    case_count: int
    input_file_count: int
    expectation_count: int


def _workspace_readme() -> str:
    return f"""# Health Data Edge Cases integration workspace

Generated by Health Data Edge Cases v{__version__}.

This workspace contains only the suite's public synthetic fixtures. Do not add
patient information, confidential identifiers, private schemas, or other
sensitive data.

## Integrate your reporting implementation

1. Run your production-equivalent transformation against each directory under
   `fixtures/`.
2. Use `result-keys.json` to shape the required metric and quality rows. It
   contains exact key tuples but no expected values.
3. Write aggregate outputs to the matching directory under `results/`, using
   the exact CSV headers already present. Empty templates intentionally produce
   an ordinary conformance failure until your implementation writes results.
4. Verify every case against this installed suite release:

   ```bash
   health-data-edge-cases verify --results results
   ```

Exit code `0` means all published expectations matched, `1` means valid outputs
did not match (including untouched templates), and `2` means the workspace or
CSV input was malformed. A pass applies only to these synthetic contracts; it
is not certification of a production system.
"""


def _write_empty_actual_csv(path: Path, columns: tuple[str, ...]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(columns)


def _raise_rename_error(error_number: int, destination: Path) -> None:
    if error_number in {errno.EEXIST, errno.ENOTEMPTY}:
        raise FileExistsError(
            error_number,
            "Refusing to replace an existing scaffold destination",
            str(destination),
        )
    raise OSError(error_number, os.strerror(error_number), str(destination))


def _publish_directory_no_replace(staging: Path, destination: Path) -> None:
    """Atomically publish ``staging`` without replacing any existing entry."""

    if os.name == "nt":
        # Windows os.rename fails when the destination already exists.
        os.rename(staging, destination)
        return

    library = ctypes.CDLL(None, use_errno=True)
    source_bytes = os.fsencode(staging)
    destination_bytes = os.fsencode(destination)

    if sys.platform.startswith("linux"):
        rename = getattr(library, "renameat2", None)
        if rename is None:
            raise OSError(
                errno.ENOSYS,
                "Atomic no-replace directory publication is unavailable",
                str(destination),
            )
        rename.argtypes = [
            ctypes.c_int,
            ctypes.c_char_p,
            ctypes.c_int,
            ctypes.c_char_p,
            ctypes.c_uint,
        ]
        rename.restype = ctypes.c_int
        if rename(-100, source_bytes, -100, destination_bytes, 1) != 0:
            _raise_rename_error(ctypes.get_errno(), destination)
        return

    if sys.platform == "darwin":
        rename = getattr(library, "renamex_np", None)
        if rename is None:
            raise OSError(
                errno.ENOSYS,
                "Atomic no-replace directory publication is unavailable",
                str(destination),
            )
        rename.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_uint]
        rename.restype = ctypes.c_int
        if rename(source_bytes, destination_bytes, 0x00000004) != 0:
            _raise_rename_error(ctypes.get_errno(), destination)
        return

    raise OSError(
        errno.ENOSYS,
        "Atomic no-replace directory publication is unavailable on this platform",
        str(destination),
    )


def create_integration_workspace(
    destination: Path,
    cases_dir: Path = DEFAULT_CASES_DIR,
) -> ScaffoldResult:
    """Create a complete external-verification workspace at a new path.

    The workspace is assembled in a private sibling directory and published by
    an atomic no-replace rename. Existing files, directories, and symlinks are
    never replaced.
    """

    destination = Path(destination)
    try:
        destination.lstat()
    except FileNotFoundError:
        pass
    else:
        raise FileExistsError(
            errno.EEXIST,
            "Refusing to replace an existing scaffold destination",
            str(destination),
        )

    parent = destination.parent
    try:
        parent_status = parent.lstat()
    except FileNotFoundError as error:
        raise ValueError(f"Destination parent does not exist: {parent}") from error
    if stat.S_ISLNK(parent_status.st_mode) or not stat.S_ISDIR(parent_status.st_mode):
        raise ValueError(
            f"Destination parent must be a regular, non-symlink directory: {parent}"
        )

    case_contracts = []
    for case_dir in discover_cases(cases_dir):
        if case_dir.is_symlink():
            raise ValueError(f"Scaffold case must not be a symlink: {case_dir}")
        manifest, metrics, quality, _ = _load_case_contract(case_dir)
        case_contracts.append((case_dir, manifest, metrics, quality))

    verification_manifest = expected_verification_manifest()
    result_keys = {
        "schema_version": "1.0.0",
        "catalog_id": verification_manifest["catalog_id"],
        "suite_version": verification_manifest["suite_version"],
        "catalog_digest": verification_manifest["catalog_digest"],
        "metric_key_columns": ["period_id", "metric_id"],
        "quality_key_columns": ["check_id"],
        "cases": [
            {
                "case_id": str(manifest["id"]),
                "metric_keys": [list(expectation.key) for expectation in metrics],
                "quality_keys": [list(expectation.key) for expectation in quality],
            }
            for _, manifest, metrics, quality in case_contracts
        ],
    }

    staging = Path(
        tempfile.mkdtemp(prefix=f".{destination.name}.tmp-", dir=parent)
    )
    try:
        fixtures_root = staging / "fixtures"
        results_root = staging / "results"
        fixtures_root.mkdir()
        results_root.mkdir()
        (staging / "README.md").write_text(_workspace_readme(), encoding="utf-8")
        (staging / "result-keys.json").write_text(
            json.dumps(
                result_keys,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        (results_root / "verification-manifest.json").write_text(
            json.dumps(
                verification_manifest,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )

        expectation_count = 0
        for case_dir, manifest, metrics, quality in case_contracts:
            case_id = str(manifest["id"])
            fixture_destination = fixtures_root / case_id
            result_destination = results_root / case_id
            fixture_destination.mkdir()
            result_destination.mkdir()

            for filename in ("case.json", *INPUT_SCHEMAS):
                source = case_dir / filename
                if not source.is_file() or source.is_symlink():
                    raise ValueError(
                        f"Scaffold source must be a regular file: {source}"
                    )
                (fixture_destination / filename).write_bytes(source.read_bytes())

            for filename, columns in ACTUAL_SCHEMAS.items():
                _write_empty_actual_csv(result_destination / filename, columns)
            expectation_count += len(metrics) + len(quality)

        # mkdtemp intentionally starts at 0700. Match the normal umask-derived
        # directory mode used for the workspace's children before publication
        # so a shared service account is not surprised by a private root.
        staging.chmod(stat.S_IMODE(fixtures_root.stat().st_mode))
        _publish_directory_no_replace(staging, destination)
    except BaseException:
        shutil.rmtree(staging, ignore_errors=True)
        raise

    return ScaffoldResult(
        destination=destination,
        case_count=len(case_contracts),
        input_file_count=len(case_contracts) * len(INPUT_SCHEMAS),
        expectation_count=expectation_count,
    )
